<?php

namespace App\Filament\Resources\System\ApiKeys\Schemas;

use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Illuminate\Support\Str;
use Filament\Schemas\Schema;

class ApiKeyForm
{
    public static function configure(Schema $schema): Schema
    {
        $operation = $schema->getOperation();

        return match ($operation) {
            'create' => self::getCreateSchema($schema),
            'edit'   => self::getEditSchema($schema),
            'view'   => self::getViewSchema($schema),
            default  => $schema,
        };
    }

    protected static function getCreateSchema(Schema $schema): Schema
    {
        return $schema->components(self::getFormComponents());
    }

    protected static function getEditSchema(Schema $schema): Schema
    {
        return $schema->components(self::getFormComponents());
    }

    protected static function getViewSchema(Schema $schema): Schema
    {
        return $schema->components(self::getFormComponents());
    }

    protected static function getFormComponents(): array
    {
        return [
            Grid::make(3)
                ->schema([
                    Grid::make(1)
                        ->columnSpan(2)
                        ->schema([
                            Section::make('Credential Information')
                                ->description('This key will be used by the Frontend (Nuxt/Next.js) to access Tenant data.')
                                ->schema([
                                    TextInput::make('name')
                                        ->label('Name')
                                        ->placeholder('Example: Nuxt.js Frontend Production')
                                        ->required(),

                                    TextInput::make('token')
                                        ->label('Secret Token (API Key)')
                                        ->default(fn () => 'nxv_' . Str::random(40))
                                        ->readOnly()
                                        ->unique(ignoreRecord: true)
                                        ->helperText('This token is automatically generated by the system.'),
                                ]),
                        ]),
                    Grid::make(1)
                        ->columnSpan(1)
                        ->schema([
                            Section::make('Settings & Access Rights')
                                ->schema([
                                    Select::make('tenant_id')
                                        ->label('Tenant')
                                        ->relationship('tenant', 'name')
                                        ->searchable()
                                        ->preload()
                                        ->required(),

                                    Select::make('is_active')
                                        ->label('Access Status')
                                        ->options([
                                            1 => 'Active (Allow API)',
                                            0 => 'Inactive (Block API)',
                                        ])
                                        ->default(1)
                                        ->required()
                                        ->helperText('If blocked, the tenant website will immediately lose data access.'),
                                ]),
                        ]),
                ])
                ->columnSpanFull(),
        ];
    }
}
